name: CodeCov
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Generate Report
      run: |
        pip install PyYaml==5.4.1
        pip install sktime==0.13.2
        python setup.py install
        pip install coverage
        coverage run --source=bulian -m unittest discover -s tests -p "runner.py"
        coverage report
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
